/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp DBus.xml -a DBusAdaptor -i DBusAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "DBusAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
/*
 * Implementation of adaptor class ClientAdaptor
 */

ClientAdaptor::ClientAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ClientAdaptor::~ClientAdaptor()
{
    // destructor
}

void ClientAdaptor::Notify(const QString &msg)
{
    // handle method call com.Skype.API.Client.Notify
    QMetaObject::invokeMethod(parent(), "Notify", Q_ARG(QString, msg));
}

