/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp DBus.xml -a DBusAdaptor -i DBusAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSADAPTOR_H
#define DBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.Skype.API.Client
 */
class ClientAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.Skype.API.Client")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.Skype.API.Client\">\n"
"    <method name=\"Notify\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"msg\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ClientAdaptor(QObject *parent);
    virtual ~ClientAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Notify(const QString &msg);
Q_SIGNALS: // SIGNALS
};

#endif
